spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PowerUpDB
    username: postgres
    password: 724036
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: create

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: 882c3947bc1163e2489059d4e2f6294fe3d5ea987245e55ac47f02d4921abdb6
  lifetime: 10m
